package com.martin.district.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "district".
 */
public class DistrictInfo {

    private long adCode;
    /** Not-null value. */
    private String name;
    private int cityCode;

    public DistrictInfo() {
    }

    public DistrictInfo(long adCode) {
        this.adCode = adCode;
    }

    public DistrictInfo(long adCode, String name, int cityCode) {
        this.adCode = adCode;
        this.name = name;
        this.cityCode = cityCode;
    }

    public long getAdCode() {
        return adCode;
    }

    public void setAdCode(long adCode) {
        this.adCode = adCode;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public int getCityCode() {
        return cityCode;
    }

    public void setCityCode(int cityCode) {
        this.cityCode = cityCode;
    }

    @Override
    public String toString() {
        return "DistrictInfo{" +
                "adCode=" + adCode +
                ", name='" + name + '\'' +
                ", cityCode=" + cityCode +
                '}';
    }
}
